profile:
  target: default
  outputs:
    default:
      type: postgres
      host: localhost
      # IMPORTANT: Make sure to quote the entire Jinja string here
      user: '{{ env_var(''DB_USER'') }}'
      password: '{{ env_var(''DB_USER_PASSWORD'') }}'
      port: 5432
      dbname: '{{ env_var(''DB_NAME'')}}'
      schema: public
