"""add last_crash_date field to etl_status table to track last date from which update is required

Revision ID: 5df5f90c46b2
Revises: ffc28bf6afaf
Create Date: 2025-06-08 19:19:45.374268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df5f90c46b2'
down_revision: Union[str, None] = 'ffc28bf6afaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_status', sa.Column('last_crash_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etl_status', 'last_crash_date')
    # ### end Alembic commands ###
