"""create vehicle and person tables

Revision ID: 62747d3e78b0
Revises: 9ca5c918caff
Create Date: 2025-06-07 16:36:43.087283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62747d3e78b0'
down_revision: Union[str, None] = '9ca5c918caff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crash',
    sa.Column('crash_id', sa.Integer(), nullable=False),
    sa.Column('crash_date', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('crash_id')
    )
    op.create_table('vehicle',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('crash_id', sa.Integer(), nullable=False),
    sa.Column('travel_direction', sa.String(), nullable=True),
    sa.Column('vehicle_occupants', sa.Integer(), nullable=True),
    sa.Column('driver_license_status', sa.String(), nullable=True),
    sa.Column('pre_crash', sa.String(), nullable=True),
    sa.Column('point_of_impact', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crash_id'], ['crash.crash_id'], ),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('person',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('crash_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('person_type', sa.String(), nullable=True),
    sa.Column('person_injured', sa.String(), nullable=True),
    sa.Column('person_age', sa.Integer(), nullable=True),
    sa.Column('person_sex', sa.String(), nullable=True),
    sa.Column('safety_equipment', sa.String(), nullable=True),
    sa.Column('position_in_vehicle', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crash_id'], ['crash.crash_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.unique_id'], ),
    sa.PrimaryKeyConstraint('unique_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    op.drop_table('vehicle')
    op.drop_table('crash')
    # ### end Alembic commands ###
