"""add borough and zip_code columns to crash table

Revision ID: 7cca8d71af16
Revises: 5df5f90c46b2
Create Date: 2025-06-10 20:45:52.698474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cca8d71af16'
down_revision: Union[str, None] = '5df5f90c46b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crash', sa.Column('borough', sa.String(), nullable=True))
    op.add_column('crash', sa.Column('zip_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crash', 'zip_code')
    op.drop_column('crash', 'borough')
    # ### end Alembic commands ###
