"""fix person_injury field name in person table

Revision ID: ffc28bf6afaf
Revises: 56bf11d3cee8
Create Date: 2025-06-08 00:46:58.595118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc28bf6afaf'
down_revision: Union[str, None] = '56bf11d3cee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('person_injury', sa.String(), nullable=True))
    op.drop_column('person', 'person_injured')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('person_injured', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('person', 'person_injury')
    # ### end Alembic commands ###
